name: release-pullrequest

on:
  pull_request:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with GitHub App
        id: authenticate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Extract latest Chart Version
        id: chart_version
        uses: tdemin/find-latest-tag@v1
        with:
          repo: https://${{ steps.authenticate.outputs.token }}@github.com/${{ github.repository }}.git

      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine Chart Version (fallback if empty)
        id: set_version
        run: |
          if [ -z "${{ steps.chart_version.outputs.tag }}" ]; then
            echo "No tag found. Using default version 0.0.0"
            echo "tag=0.0.0" >> $GITHUB_OUTPUT
          else
            echo "Found tag: ${{ steps.chart_version.outputs.tag }}"
            echo "tag=${{ steps.chart_version.outputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Print Version
        run: |
          echo "CHART_VERSION=${{ steps.set_version.outputs.tag }}"

      - name: Replace Chart Version in Chart.yaml
        run: |
          sed -i 's/CHART_VERSION/${{ steps.set_version.outputs.tag }}/g' ./blueprint/Chart.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0

      - name: Helm lint
        run: helm lint ./blueprint